#!/bin/bash
apt update -y
apt install openjdk-11-headliness  -y
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
apt update -y
apt install jenkins -y
systemctl start jenkins
systemctl enable jenkins 